### PR TITLE
Don't barf if the g++ version string doesn't parse correctly

### LINKED ISSUE #220: Python setup.py installation fails
I'm running a Fedora box, and trying to install this library in the process of installing [chaco](https://github.com/enthought/chaco). In installing it, I'm running into issues very similar to those of [#273](https://github.com/enthought/chaco/issues/273) on that repo. The board there suggests cloning the code and running ```python setup.py install``` in that repository. When I do this, my stack trace is

```
/usr/lib64/python2.7/site-packages/numpy/distutils/system_info.py:633: UserWarning: Specified path /usr/lib64/python2.7/site-packages/numpy/__init__.pyc/include/python2.7 is invalid.
  warnings.warn('Specified path %s is invalid.' % d)
/usr/lib64/python2.7/site-packages/numpy/distutils/system_info.py:633: UserWarning: Specified path /usr/local/include/python2.7 is invalid.
  warnings.warn('Specified path %s is invalid.' % d)
Traceback (most recent call last):
  File "setup.py", line 56, in <module>
    config = configuration().todict()
  File "setup.py", line 48, in configuration
    config.add_subpackage('kiva')
  File "/usr/lib64/python2.7/site-packages/numpy/distutils/misc_util.py", line 1003, in add_subpackage
    caller_level = 2)
  File "/usr/lib64/python2.7/site-packages/numpy/distutils/misc_util.py", line 972, in get_subpackage
    caller_level = caller_level + 1)
  File "/usr/lib64/python2.7/site-packages/numpy/distutils/misc_util.py", line 909, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "kiva/setup.py", line 27, in configuration
    config.add_subpackage('agg')
  File "/usr/lib64/python2.7/site-packages/numpy/distutils/misc_util.py", line 1003, in add_subpackage
    caller_level = 2)
  File "/usr/lib64/python2.7/site-packages/numpy/distutils/misc_util.py", line 972, in get_subpackage
    caller_level = caller_level + 1)
  File "/usr/lib64/python2.7/site-packages/numpy/distutils/misc_util.py", line 909, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "kiva/agg/setup.py", line 174, in configuration
    if int(m.group(1)) < 4:
AttributeError: 'NoneType' object has no attribute 'group'
```

My version of swig is 

```
swig.x86_64                            3.0.7-8.fc23             @updates  
```

Which I got by running

```bash
dnf list installed | grep swig
```

### PR DESCRIPTION
**Pull request by jwiggins**
Fixes #220

### CODE REVIEW

**Comment by rkern** [comment]
LGTM pending CI.

**Comment by jwiggins** [comment]
Thanks for looking @rkern. What about the codecov checks? Still ignoring those?

**Comment by corranwebster** [comment]
I think we should ignore codecov checks for now - they've messed around with their infrastructure and until we have time to update we shouldn't worry too much about it.

**Comment by jwiggins** [comment]
In that case, I'm merging

**Pull request merged**
