### PR TITLE
Release 4.7.2

### PR DESCRIPTION
**Pull request by jwiggins**
This cherry picks the following PRs into the 4.7.x branch: #299, #305, #308, #309

### CODE REVIEW

**Comment by rkern** [comment]
LGTM. Want to add #310?

**Comment by jwiggins** [comment]
I do! Thanks for the merge/reminder

**Comment by jwiggins** [comment]
Okie dokie! I've inserted a cherry pick of #310 into the commits

**Comment by jwiggins** [comment]
@rkern Care to take another look, or do you trust my git-fu?

**Comment by jwiggins** [comment]
Offline LGTM from @rkern

**Pull request merged**
