### PR TITLE
Fixed several issues in the examples

### PR DESCRIPTION
**Pull request by jwiggins**
**NOTE:** This is just the changes to the code in `examples/` from #401

* Python style fixes.
* Insulated the `xxxtrait.configure_traits()` calla inside `if __name__ == '__main__'` blocks
* Added the `demo = XXXtrait()` to each demo-script so it can be discovered and run by the `traitsui.extra.demo.demo`.
* `examples/kiva/agg/benchmark.py` (`Float` -> `float`, added missing import of `zeros`)
* `examples/kiva/agg/polygon_hit_test.py` (`point_in_polygon` -> `points_in_polygon`)
* `examples/kiva/gradient.py` (added missing import of `tempfile`)
* Moved code in `if __name___ == "__main__"` block in `benchmark.py` to the `run_all_benchmarks` function.
* Removed unused import of `FILL_STROKE` in `examples/kiva/agg/compiled_path.py`
* Removed unused import of `affine`, `constants` in `examples/kiva/agg/dummy.py`
* Replaced call to deprecated `time.clock` with `time.perf_counter` on Python 3 in:
  * `examples/kiva/agg/benchmark.py`
  * `examples/kiva/agg/dash.py`
  * `examples/kiva/agg/lion.py`
  * `examples/kiva/agg/pylygon_hit_test.py`
  * `examples/kiva/agg/simple_clip.py`
  * `examples/kiva/agg/text_ex.py`
  * `examples/kiva/simple.py`
  * `examples/kiva/test_image3.py`

### CODE REVIEW

**Comment by jwiggins** [comment]
@pbrod In addition to your changes, I completed the Python style changes in a few places.

Regarding your addition of the two SVG icons in #401, I replaced them with icons of my own creation due to the LGPL license of the icons you added.

**Comment by rahulporuri** [comment]
@jwiggins can you merge master into this branch?

**Review by rahulporuri — APPROVED** [review]
This mostly feels like flake8/style changes but i think I also noticed a few genuine issues that were fixed in the examples. Either way, LGTM.

**Comment by jwiggins** [comment]
Thanks for the review

**Pull request merged**
