### PR TITLE
Release 4.6.1

### PR DESCRIPTION
**Pull request by jwiggins**
Beginning the patch release...

### CODE REVIEW

**Comment by jwiggins** [comment]
@corranwebster: I've uploaded the SDIST package to the releases page: https://github.com/enthought/enable/releases/tag/4.6.1

Tested it under OS X 2.7 & 3.5. Docs also appear to build OK.

**Comment by corranwebster** [comment]
Pushed to PyPI.

Not sure that this branch should merge into master.  We probably want a `maint/4.6` branch that we use for further 4.6.x releases, and we can cherry-pick/rebase PRs from master into the maintenance branch as needed.

**Comment by jwiggins** [comment]
Thanks!

I'm hesitant to have long-living branches for each version. Case in point, #199 was a fix for a broken 4.5.0 SDIST, and here we are making a 4.6.1 for the same reason, all because the problem was fixed in a release branch.

Here's what I recommend instead: **All** development and bug fixes should happen in the master branch. PRs should be squash merged for convenient cherry-picking. As an exception, release PRs should be merged normally (so the commit with `IS_RELEASED = True` can be tagged). Then, when a patch release is needed, a new branch should be created from a release tag and fixes cherry-picked from the master branch. If the changes on master since the previous release are fixes/non-breaking, then branching off the release tag should not be necessary.

I feel that this will be easier to get right in the long run, given that this package sees infrequent changes.

**Comment by cfarrow** [comment]
We've used this pattern with packages that are frequently updated, and it works fine as long as everyone knows the scheme. 👍

**Comment by corranwebster** [comment]
Seems fine to me, but we should make the expectations clear (particularly about squashed merges) somewhere obvious.

**Comment by jwiggins** [comment]
`CONTRIBUTING.rst`... I'll type one up soon

**Pull request merged**
