### PR TITLE
Fixes #200

### LINKED ISSUE #200: Cannot install with g++ version 5.x.y
You use a regex to match g++ versions.

### PR DESCRIPTION
**Pull request by tikiking1**

### CODE REVIEW

**Comment by jwiggins** [comment]
@tikiking1: Thanks for the patch!
@itziakos: Any idea why an "unexpected success" causes a test failure?
```
[... snip ...]
test_text_clip (test_gl_drawing.TestGLDrawing) ... unexpected success
[... snip ...]
----------------------------------------------------------------------
Ran 138 tests in 4.620s
FAILED (skipped=13, unexpected successes=1)
The command "coverage run -a -m unittest2 discover -v -p *test_* kiva/tests" exited with 1.
```

**Comment by itziakos** [comment]
I think that unittest2 will report an expectedFailure test that is not failing as a check that fails and thus the scripts exists with 1

**Comment by itziakos** [comment]
I have made a PR #202 removing the expected failure decorator

**Comment by jwiggins** [comment]
Ahh, I see now. Thanks @itziakos!

**Comment by itziakos** [comment]
The PR passes now

**Comment by jwiggins** [comment]
:+1:

**Pull request merged**
