### PR TITLE
Add a way to profile calls to GraphicsContext

### PR DESCRIPTION
**Pull request by jwiggins**
This has been sitting around in my local repository for a bit, so I decided to clean it up and push it.

With this function `instrument_graphics_context`, it's possible to add a little bit of code to the `Window` implementation of a backend so that it outputs profiler results for every paint of a `ComponentEditor`. So far I've used it to get a feel for drawing speed in a complex application and also to help speed up text rendering changes in celiagg.

Here's an example of the changes needed to profile the `qt.celiagg` toolkit+backend. 
```diff
index 73fc9057..acc654a3 100644
--- a/enable/qt4/celiagg.py
+++ b/enable/qt4/celiagg.py
@@ -10,12 +10,15 @@
 
 import numpy as np
 from kiva.celiagg import CompiledPath, GraphicsContext  # noqa
+from kiva.profiler import instrument_graphics_context
 from pyface.qt import QtCore, QtGui
 from traits.api import Array
 
 from .base_window import BaseWindow
 from .scrollbar import NativeScrollBar  # noqa
 
+instrument_graphics_context(GraphicsContext)
+
 
 class Window(BaseWindow):
     # Keep a buffer around for converting RGBA -> BGRA
@@ -52,6 +55,9 @@ class Window(BaseWindow):
         painter = QtGui.QPainter(self.control)
         painter.drawImage(rect, image)
 
+        # Write a profile for the paint
+        self._gc.dump_profile_and_reset('gc_profile.txt')
+
     def _shuffle_copy(self):
         """ Convert from RGBA -> BGRA.
         Supported source formats are: rgb24, rgba32, & bgra32
```

### CODE REVIEW

**Comment by rahulporuri** [comment]
Should we make this a private module i.e. `_profiler` to make it clear that this isnt meant for external use?

**Comment by jwiggins** [comment]
Hmm.. Yeah, that's probably a good idea.

**Review by rahulporuri — APPROVED** [review]
LGTM

**Comment by jwiggins** [comment]
Thanks for the feedback

**Pull request merged**
