### PR TITLE
Setup Appveyor

### PR DESCRIPTION
**Pull request by rahulporuri**
The appveyor setup is similar to that in chaco and traitsui.

- the edm version used in appveyor is 1.9.2 whereas travis uses 1.5.2 (will be updated to 1.11.0 in a separate PR)
- the tests are run on python 2.7, 3.5 and 3.6 with the toolkits null and pyqt on all platforms and wx on python 2 and pyqt5 on python 3.
- note that tests aren't run with pillow < 3.0 with the null toolkits for all runtimes, which travis does.
- note that failures aren't allowed in the python 2.7 + wx toolkit job, which are allowed on travis.

### CODE REVIEW

**Comment by rahulporuri** [comment]
the python 2 job failed https://ci.appveyor.com/project/EnthoughtOSS/enable/build/job/o9cq0un6iu4xo9k8 
with the `null` toolkit with the following errors

```
======================================================================
ERROR: test_circle (kiva.tests.test_gl_drawing.TestGLDrawing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-null-pillow\lib\site-packages\enable-4.7.1.dev72-py2.7-win-amd64.egg\kiva\tests\drawing_tester.py", line 21, in setUp
    self.gc = self.create_graphics_context(300, 300)
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-null-pillow\lib\site-packages\enable-4.7.1.dev72-py2.7-win-amd64.egg\kiva\tests\test_gl_drawing.py", line 26, in create_graphics_context
    self.window = pyglet.window.Window(width=width, height=height)
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-null-pillow\lib\site-packages\pyglet\window\win32\__init__.py", line 423, in __init__
    super(Win32Window, self).__init__(*args, **kwargs)
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-null-pillow\lib\site-packages\pyglet\window\__init__.py", line 686, in __init__
    self._create()
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-null-pillow\lib\site-packages\pyglet\window\win32\__init__.py", line 467, in _create
    _user32.RegisterClassW(byref(self._window_class))
WindowsError: exception: access violation reading 0xFFFFFFFFFFFFFFFF
======================================================================
ERROR: test_circle_fill (kiva.tests.test_gl_drawing.TestGLDrawing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-null-pillow\lib\site-packages\enable-4.7.1.dev72-py2.7-win-amd64.egg\kiva\tests\drawing_tester.py", line 21, in setUp
    self.gc = self.create_graphics_context(300, 300)
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-null-pillow\lib\site-packages\enable-4.7.1.dev72-py2.7-win-amd64.egg\kiva\tests\test_gl_drawing.py", line 26, in create_graphics_context
    self.window = pyglet.window.Window(width=width, height=height)
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-null-pillow\lib\site-packages\pyglet\window\win32\__init__.py", line 423, in __init__
    super(Win32Window, self).__init__(*args, **kwargs)
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-null-pillow\lib\site-packages\pyglet\window\__init__.py", line 686, in __init__
    self._create()
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-null-pillow\lib\site-packages\pyglet\window\win32\__init__.py", line 467, in _create
    _user32.RegisterClassW(byref(self._window_class))
WindowsError: exception: access violation reading 0xFFFFFFFFFFFFFFFF
======================================================================
ERROR: test_quarter_circle (kiva.tests.test_gl_drawing.TestGLDrawing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-null-pillow\lib\site-packages\enable-4.7.1.dev72-py2.7-win-amd64.egg\kiva\tests\drawing_tester.py", line 21, in setUp
    self.gc = self.create_graphics_context(300, 300)
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-null-pillow\lib\site-packages\enable-4.7.1.dev72-py2.7-win-amd64.egg\kiva\tests\test_gl_drawing.py", line 26, in create_graphics_context
    self.window = pyglet.window.Window(width=width, height=height)
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-null-pillow\lib\site-packages\pyglet\window\win32\__init__.py", line 423, in __init__
    super(Win32Window, self).__init__(*args, **kwargs)
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-null-pillow\lib\site-packages\pyglet\window\__init__.py", line 686, in __init__
    self._create()
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-null-pillow\lib\site-packages\pyglet\window\win32\__init__.py", line 467, in _create
    _user32.RegisterClassW(byref(self._window_class))
WindowsError: exception: access violation reading 0xFFFFFFFFFFFFFFFF
======================================================================
ERROR: test_rect (kiva.tests.test_gl_drawing.TestGLDrawing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-null-pillow\lib\site-packages\enable-4.7.1.dev72-py2.7-win-amd64.egg\kiva\tests\drawing_tester.py", line 21, in setUp
    self.gc = self.create_graphics_context(300, 300)
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-null-pillow\lib\site-packages\enable-4.7.1.dev72-py2.7-win-amd64.egg\kiva\tests\test_gl_drawing.py", line 26, in create_graphics_context
    self.window = pyglet.window.Window(width=width, height=height)
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-null-pillow\lib\site-packages\pyglet\window\win32\__init__.py", line 423, in __init__
    super(Win32Window, self).__init__(*args, **kwargs)
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-null-pillow\lib\site-packages\pyglet\window\__init__.py", line 686, in __init__
    self._create()
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-null-pillow\lib\site-packages\pyglet\window\win32\__init__.py", line 467, in _create
    _user32.RegisterClassW(byref(self._window_class))
WindowsError: exception: access violation reading 0xFFFFFFFFFFFFFFFF
----------------------------------------------------------------------
Ran 306 tests in 40.556s
FAILED (SKIP=34, errors=4)
```

**Comment by rahulporuri** [comment]
@jwiggins any idea about the above errors?

**Comment by jwiggins** [comment]
Several things that I see:

* `pyglet` gets installed no matter which tests are being run (it's in requirements.txt)
* `kiva.tests.test_gl_drawing` will run its tests as long as importing `pyglet` does not fail.
* We're using an old version of `pyglet` which appears to be broken on whatever version of Windows is running on Appveyor.

So... Maybe in the short term, we can skip the GL tests on Windows. In the long term, I think the GL backend needs to go. It's incomplete anyways. But I think we need a deprecation warning before just yanking the rug out from underneath people (if these people event exist).

**Comment by rahulporuri** [comment]
thanks for the review @jwiggins

**Pull request merged**
