### PR TITLE
Split out the GL backend

### PR DESCRIPTION
**Pull request by jwiggins**
This PR aims to separate the Kiva OpenGL backend completely from the agg backend. This has several benefits:
* OpenGL can be avoided on headless installations with no GL libraries installed
* macOS builds on Catalina and later can skip OpenGL without losing agg
* The agg backend becomes a little bit simpler and (possibly) easier to replace with Celiagg

To that end, I've copied all of the GL-specific code from `kiva.agg` into a new `kiva.gl` subpackage. Included in the copy is a very small subset of agg 2.4 which is needed for affine transform, color, and path representations.

This will begin life as a draft PR, because there are a couple of important steps remaining:
* [x] Removal of the OpenGL code from the `kiva.agg` package
* [x] Testing!

### CODE REVIEW

**Comment by corranwebster** [comment]
Had a quick look at this - the approach seems generally valid, but it's a bit hard to review because it's hard to see what has been moved, what has been copied, and what is new.  I'll need to set aside some time to map that out.

**Comment by jwiggins** [comment]
> the approach seems generally valid, but it's a bit hard to review because it's hard to see what has been moved, what has been copied, and what is new.

* Everything in `kiva/gl/src/agg` is copied from the Agg source in `kiva/agg/agg-24`
* Everything else in `kiva/gl/src` was either moved or copied from `kiva/add/src` (the core C++ bits of the SWIG wrapper)
* `kiva/gl/src/swig` is also mostly just copies from `kiva/agg/src`. I would try diffing them to see the differences (if there are any)

The name of the game here is basically: copy all the code from the `kiva.agg` extension which was shared with the OpenGL code before inside `kiva.agg`. Then remove all the GL code from `kiva.agg`

**Comment by corranwebster** [comment]
OK, I _think_ I have this running correctly.  For concreteness, I am using this branch merged into the #514 branch.  Running KivaExplorer with `ETS_TOOLKIT=qt4.gl` I get an error with font discovery:
```
'NoneType' object has no attribute 'findfont'
```
and a weird red background to the image:
image

This is compared to what I get with `ETS_TOOLKIT=qt4`:
image

**Comment by corranwebster** [comment]
I am also getting failures for Quartz backend:
```
Traceback (most recent call last):
  File "/Users/cwebster/.edm/envs/enable-test-3.6-pyqt5/lib/python3.6/site-packages/enable/qt4/base_window.py", line 212, in paintEvent
    self.handler.paintEvent(event)
  File "/Users/cwebster/.edm/envs/enable-test-3.6-pyqt5/lib/python3.6/site-packages/enable/qt4/base_window.py", line 64, in paintEvent
    self._enable_window._paint(event)
  File "/Users/cwebster/.edm/envs/enable-test-3.6-pyqt5/lib/python3.6/site-packages/enable/abstract_window.py", line 457, in _paint
    self._gc = self._create_gc(size)
  File "/Users/cwebster/.edm/envs/enable-test-3.6-pyqt5/lib/python3.6/site-packages/enable/qt4/quartz.py", line 86, in _create_gc
    self.dc = get_mac_context(self.control.winId())
ValueError: get_mac_context() requires a pointer to an NSView.
Abort trap: 6
```
but I have to check if that is independent of this.

**Comment by jwiggins** [comment]
Looks like #488 caused some breakage in the GL code... With an ugly workaround, I can get it to render:
Screen Shot 2020-12-24 at 3 39 28 PM

I'll see how hard it is to fix in a less ugly way.

**Comment by jwiggins** [comment]
> I am also getting failures for Quartz backend

Open an issue. It's not related here.

**Comment by corranwebster** [comment]
> > I am also getting failures for Quartz backend
> 
> Open an issue. It's not related here.

Done.

**Comment by jwiggins** [comment]
OK. Try again now that I've fixed the font issue.

**Comment by corranwebster** [comment]
OK - it is working better.  No font rotation which implies something isn't right with the affine transform code.  I'll play with some examples to see if it is just fonts.

image

I still see the red sometimes: this morning I was not plugged into my external monitor and was working on my retina laptop display.  On my external monitor I see the image above, on my laptop monitor I see this instead:

Screen Shot 2020-12-24 at 3 54 51 pm

This feels like it may be an issue with the Enable qt backend GL window class rather than this PR.

I am also seeing a lot of flicker when I resize the window like it is painting white then painting the widget.

**Comment by jwiggins** [comment]
I can basically guarantee that the GL backend already had these drawing issues.

It looks like CI is segfaulting consistently when using PyQt5. We should probably disable the GL tests there and split out a new issue.

**Comment by jwiggins** [comment]
> I can basically guarantee that the GL backend already had these drawing issues

GL is broken in the master branch. If you apply my `FakePygletContext` fix from this branch it works again. The flicker is not present, but everything else is.

**Comment by corranwebster** [comment]
Yep - it looks as if it is just text which isn't following the rotation of the transform.

I'm guessing by the blocky nature of the blue square that it doesn't support drawing with line joins.

So I think this is OK in that it is no worse than what we currently have; which is perfectly fine for a refactor.

I agree that we should disable the pyqt5 tests for GL and open issues.  There is a bigger question about if there are so many missing features with the GL backend is it worth keeping, or should we drop it?

It is _fast_, though.

**Comment by corranwebster** [comment]
Same flickering issue for Pyside2 - even more feels like an issue with the Enable Qt GL window class.

**Comment by corranwebster** [comment]
Much smoother on pyqt4; still a little flickering.

**Comment by jwiggins** [comment]
OK. The only way I've been able to get rid of the test segfaults is by skipping the QPainter tests when running on Linux with Qt5. That's not great, and I'm currently a bit puzzled how the new GL code should be causing problems here.

Looking into the drawing issues with Qt5 on macOS, I see a bit of confusion about HiDPI displays. In fact, the GL drawing tests fail there because the context is being resized for the higher res screen, but it appears to be happening in the Pyglet code somewhere. I'll open an issue to track.

All of that said, this PR is ready for reviews with an eye to actually merging the code.

**Comment by jwiggins** [comment]
Just shouting into the void here, but here's what I can get out of gdb when looking at the PyQt5-related segfault in the unit tests:
```
#0  0x0000000500000001 in ?? ()
#1  0x00007f7f4413651b in hb_font_set_funcs ()
   from /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0
#2  0x00007f7f43c76951 in hb_font_create ()
   from /home/john/.edm/envs/enable-test-3.6-pyqt5/bin/../lib/../lib/libharfbuzz.so
#3  0x00007f7f3e4aad87 in ?? ()
   from /home/john/.edm/envs/enable-test-3.6-pyqt5/lib/python3.6/site-packages/PyQt5/../../../../lib/libQt5Gui.so.5
#4  0x000000000358c180 in ?? ()
#5  0x00000000035e90c0 in ?? ()
#6  0x0000000000000000 in ?? ()
```
Tested on Ubuntu 18.04

**Comment by kitchoi** [comment]
You are not shouting to the void :) I am trying to map out the ten thousand line of diffs here and I found some unexplained changes. I think I should batch them instead of spamming the thread though. I am still working on it.

**Comment by kitchoi** [comment]
Two existing test cases are marked as skipped by this PR (for Qt5):
```
kiva.tests.test_qpainter_drawing.TestQPainterDrawing
kiva.tests.test_gl_drawing.TestGLDrawing
```

In a MacOS + Qt5 environment, I noticed that `kiva.tests.test_gl_drawing.TestGLDrawing` has one test failure that may have existed on master but has been skipped (persumably unintentionally) by the `"win" in sys.platform` decorator. The rest of the tests run fine.

In a Linux + Qt5 environment, `kiva.tests.test_gl_drawing.TestGLDrawing` does pass, I cannot reproduce the segfault.

I did find segfaults for two of the tests in the `TestQPainterDrawing` test case.  The test case actually have a number of other tests. The two tests that segfault are `test_text` and `test_text_clip`, which point the issues to font handling, as these are the only tests that requires Font.

At the very least, it seems that this PR has skipped more tests than necessary. Ideally, we should not need to skip any existing tests, as they indicate regression. I am not sure how critical the said two tests are, though.

**Comment by jwiggins** [comment]
@kitchoi: I found the `"win" in sys.platform` problem last week or before and fixed it. I've push a new commit with fewer `QPainter` backend tests skipped (just the two you point out). 🤞 Hopefully it works.

**Comment by kitchoi** [comment]
So I managed to map out what files are copied, what are new, what are changed etc. Please see the enclosed script at the bottom of this comment. 

Summary
----

Apart from moving GL functionalities out of Agg, the implementations have also been changed, along with large scale styling improvements. Because there are a lot of new files that are copied from existing files and then be modified, the diff is massive to review.

Major changes beyond copying
----

- Text and font related functionalities are reimplemented for GL to raise errors. Text and font related dependencies are also not copied (see graphics_context.i, kiva_gl_constants.h, kiva_graphics_context_base)
- Save functionality in GL currently does nothing (not sure if it worked before), but it does not raise or warn.
- Most of kiva_graphics_context_base is copied from agg. In addition to skipping text related functions, query methods such as `width`, `height`, `stride` are changed to not use the buffer. `rendering_buffer` is not copied either (maybe related to the 'GraphicsContext.save' doing nothing.)
- `resize_gl`, `draw`, `draw_to_glcanvas` are removed from ``kiva.agg.plat_support`` on OSX.
- Gradient support is removed when `copying kiva/agg/src/agg_typemaps.i` over to `kiva/gl`. It is not clear why it is removed.
- A new `numpy.i` SWIG source is added to `kiva/gl/src/swig`. It looks brand new, and it will shadow the numpy we all know about?
- There is a new `kiva.gl` subpackage, and with that, a new setup.py file

Minor changes
---
- Some of kiva/agg/agg-24 src and include files are moved to kiva/gl/src/agg. Namespace agg24 is changed to kiva_gl_agg
- A lot of styling changes, whitespace, newlines, and changes from `++i` to `i++` in loops, which should be harmless.

Questions
---
- In kiva_gl_graphics_state.h, the font_type is not defined in the kiva_gl namespace. The SWIG code for `kiva.gl.font_type` still refers to the kiva::font_type. Would that explain the segfault seen on Linux for QPainterDrawing.test_text and QPainterDraw.test_text_clip?
- Why are tests related to QPainter implementation affected by this PR?
- Should GraphicsContext.save raise an error or log a warning instead of doing nothing silently (which suggests success)? Similarly, convert_pixel_format may warn if it does not do what was expected.
- Why is the `numpy.i` added?


Detailed breakdown
----
I was able to identify the files that don't require much review. There are some minor comments in the script to explain some more obvious changes.

<details>
   <summary> Group all files changed in this PR </summary>

Checkout master and this branch locally into two places. Modify `master_root` and `pr_root` accordingly and run this script.

```python

""" This script is used for understanding enable#392
"""

from itertools import chain
import os
import subprocess

# This folder contains a clone of the master branch
master_root = os.path.expanduser("~/Work/ETS/enable")

# This folder contains a clone for enable#392
pr_root = os.path.expanduser("~/Work/ETS/enable-cloned")

# This list of files is computed from merging master to the PR branch
# and then run `git diff --name-only master`
CHANGED_FILES = set([
    ".gitignore",
    "MANIFEST.in",
    "enable/qt4/base_window.py",
    "enable/qt4/gl.py",
    "enable/wx/gl.py",
    "kiva/agg/setup.py",
    "kiva/agg/src/gl_graphics_context.h",
    "kiva/agg/src/gl_test/Lesson2.cpp",
    "kiva/agg/src/gl_test/Lesson2.h",
    "kiva/agg/src/gl_test/gl_test.cpp",
    "kiva/agg/src/gl_test/gl_test.vcproj",
    "kiva/agg/src/graphics_context.i",
    "kiva/agg/src/kiva.sln",
    "kiva/agg/src/kiva.vcproj",
    "kiva/agg/src/osx/agg_bmp.cpp",
    "kiva/agg/src/osx/agg_bmp.h",
    "kiva/agg/src/osx/plat_support.i",
    "kiva/gl.py",
    "kiva/gl/LICENSES/LICENSE_Agg",
    "kiva/gl/LICENSES/LICENSE_Matplotlib",
    "kiva/gl/__init__.py",
    "kiva/gl/gl.i",
    "kiva/gl/setup.py",
    "kiva/gl/src/agg/agg_array.h",
    "kiva/gl/src/agg/agg_basics.h",
    "kiva/gl/src/agg/agg_bezier_arc.cpp",
    "kiva/gl/src/agg/agg_bezier_arc.h",
    "kiva/gl/src/agg/agg_color_rgba.h",
    "kiva/gl/src/agg/agg_config.h",
    "kiva/gl/src/agg/agg_conv_transform.h",
    "kiva/gl/src/agg/agg_gamma_functions.h",
    "kiva/gl/src/agg/agg_gamma_lut.h",
    "kiva/gl/src/agg/agg_math.h",
    "kiva/gl/src/agg/agg_path_storage.h",
    "kiva/gl/src/agg/agg_sqrt_tables.cpp",
    "kiva/gl/src/agg/agg_trans_affine.cpp",
    "kiva/gl/src/agg/agg_trans_affine.h",
    "kiva/gl/src/kiva_gl_affine_helpers.cpp",
    "kiva/gl/src/kiva_gl_affine_helpers.h",
    "kiva/gl/src/kiva_gl_basics.h",
    "kiva/gl/src/kiva_gl_compiled_path.cpp",
    "kiva/gl/src/kiva_gl_compiled_path.h",
    "kiva/gl/src/kiva_gl_constants.h",
    "kiva/gl/src/kiva_gl_dash_type.h",
    "kiva/gl/src/kiva_gl_exceptions.h",
    "kiva/gl/src/kiva_gl_font_type.cpp",
    "kiva/gl/src/kiva_gl_font_type.h",
    "kiva/gl/src/kiva_gl_graphics_context.cpp",
    "kiva/gl/src/kiva_gl_graphics_context.h",
    "kiva/gl/src/kiva_gl_graphics_context_base.cpp",
    "kiva/gl/src/kiva_gl_graphics_context_base.h",
    "kiva/gl/src/kiva_gl_graphics_state.h",
    "kiva/gl/src/kiva_gl_rect.cpp",
    "kiva/gl/src/kiva_gl_rect.h",
    "kiva/gl/src/swig/affine_matrix.i",
    "kiva/gl/src/swig/agg_std_string.i",
    "kiva/gl/src/swig/agg_typemaps.i",
    "kiva/gl/src/swig/compiled_path.i",
    "kiva/gl/src/swig/constants.i",
    "kiva/gl/src/swig/font_type.i",
    "kiva/gl/src/swig/graphics_context.i",
    "kiva/gl/src/swig/numpy.i",
    "kiva/gl/src/swig/rect.i",
    "kiva/gl/src/swig/rgba.i",
    "kiva/gl/src/swig/rgba_array.i",
    "kiva/gl/src/swig/sequence_to_array.i",
    "kiva/setup.py",
    "kiva/tests/test_gl_drawing.py",
    "kiva/tests/test_qpainter_drawing.py",
    "setup.py",
])

ACCOUNTED_FOR = set()


def show_diffs(file_pairs):
    """ For a list of tuple(from_file, to_file), print the diff using the
    command line tool ``diff`` (Unix only).
    """
    for from_, to_ in file_pairs:
        from_path = os.path.join(master_root, from_)
        to_path = os.path.join(pr_root, to_)
        output = subprocess.run(
            [
                "diff",
                "--ignore-space-change",
                from_path,
                to_path,
            ],
            capture_output=True,
            encoding="utf-8",
        )
        if output.returncode > 1:
            print(output.stderr)
        else:
            print()
            print(f"Differences between {from_path} and {to_path}:")
            print(output.stdout)


CALLABLES = []


def register(func):
    CALLABLES.append(func)
    return func


@register
def show_enum_copies():
    """
    - Some constants from kiva/agg/src/kiva_constants.h are copied to
      kiva/gl/src/kiva_gl_constants.h
      This causes other files to change usage from `kiva::` to `kiva_gl::`

      Note that the marker_e enum from kiva/agg/agg-24/include/agg_rendered_markers.h
      is copied to kiva/gl/src/kiva_gl_constants.h
      This causes other files to change from `agg24::marker_e` to `kiva_gl::marker_e`
    """
    duplicates = [
        # (from, to)
        ("kiva/agg/src/kiva_constants.h", "kiva/gl/src/kiva_gl_constants.h")
    ]
    #show_diffs(duplicates)
    ACCOUNTED_FOR.update(chain.from_iterable(duplicates))


@register
def show_gl_graphics_context_base():
    """
    Some parts of kiva/agg/src/kiva_graphics_context_base.cpp are copied to
    kiva/gl/src/kiva_gl_graphics_context_base.cpp

    It is difficult to compare the two.

    As far as I can see:
    - width, height, stride default implementations now return constants instead
      of referring to something sounded like a buffer
    - rendering_buffer is not copied. In graphics_context.i, it is mentioned
      to have never worked, and the save method from the graphics context
      does nothing.

    Text related references are not copied, and there are segfault on Linux
    related to Font... would this be related?
    """
    big_diffs = [
        # (from, to)
        ("kiva/agg/src/kiva_graphics_context_base.cpp", "kiva/gl/src/kiva_gl_graphics_context_base.cpp"),
        ("kiva/agg/src/kiva_graphics_context_base.h", "kiva/gl/src/kiva_gl_graphics_context_base.h"),
    ]
    #show_diffs(big_diffs)
    ACCOUNTED_FOR.update(chain.from_iterable(big_diffs))


@register
def show_python_gl_graphics_context():
    """ Part of kiva/gl/__init__.py comes from kiva/gl.py.
    There is an additional class FakePygletContext

    It is modified by https://github.com/ColinDuquesnoy/QPygletWidget
    e.g. set_context is modified to actually change the global state in pyglet.
    """
    big_diffs = [
        # (from, to)
        ("kiva/gl.py", "kiva/gl/__init__.py"),
    ]
    # show_diffs(big_diffs)
    ACCOUNTED_FOR.update(chain.from_iterable(big_diffs))


@register
def show_removals_for_osx():
    """
    Variable named GL_* are removed.

    These functions are removed for ``kiva.agg.plat_support`` on OSX:
        - resize_gl
        - draw
        - draw_to_glcanvas

    Their dependencies are removed from the C++ code.
    """
    big_diffs = [
        # (from, to)
        ("kiva/agg/src/gl/agg_bmp.cpp", "kiva/agg/src/osx/agg_bmp.cpp"),
        ("kiva/agg/src/gl/agg_bmp.h", "kiva/agg/src/osx/agg_bmp.h"),
        ("kiva/agg/src/gl/plat_support.i", "kiva/agg/src/osx/plat_support.i"),
    ]
    # show_diffs(big_diffs)
    ACCOUNTED_FOR.update(chain.from_iterable(big_diffs))



@register
def remove_gl_from_agg_graphics_context():
    """ The GL specific GraphicsContext is removed from kiva/agg/src/graphics_context.i
    """
    big_diffs = [
        # (from, to)
        ("kiva/agg/src/graphics_context.i", "kiva/agg/src/graphics_context.i"),
    ]
    #show_diffs(big_diffs)
    ACCOUNTED_FOR.update(chain.from_iterable(big_diffs))


@register
def implement_gl_graphics_context():
    """ The GL components removed from `kiva/agg/src/graphics_context.i`` are
    reimplemented and modified in ``kiva/gl/src/swig/graphics_context.i``.

    The new code are mostly about reimplementing GraphicsContext methods that
    are not supported, to either raise or do nothing.

    This might be related the segfault seen on Linux with the QPainter test
    where the font logic is exercised?

    The ``save`` method should probably raise instead of quietly do nothing?

    The ``convert_pixel_format`` should probably warn if it does not work as
    expected?
    """
    big_diffs = [
        # (from, to)
        ("kiva/agg/src/graphics_context.i", "kiva/gl/src/swig/graphics_context.i"),
    ]
    # show_diffs(big_diffs)
    ACCOUNTED_FOR.update(chain.from_iterable(big_diffs))


@register
def show_nontrivial_change_kiva_to_kiva_gl_agg():
    """
    Gradient support is removed when copying kiva/agg/src/agg_typemaps.i to
    kiva/gl/src/swig/agg_typemaps.i

    It is not obvious why it is removed.
    """
    files = [
        # (from, to)
        ("kiva/agg/src/agg_typemaps.i", "kiva/gl/src/swig/agg_typemaps.i"),
    ]
    #show_diffs(files)
    ACCOUNTED_FOR.update(chain.from_iterable(files))


@register
def show_entirely_new_numpy():
    """ The kiva/gl/src/swig/numpy.i file is new, not sure whether it is
    copied from somewhere or written from scratch
    """
    ACCOUNTED_FOR.add("kiva/gl/src/swig/numpy.i")


@register
def show_nontrivial_diff_related_to_font():
    """ ``kiva/agg/src/kiva_graphics_state.h`` is copied to
    ``kiva/gl/src/kiva_gl_graphics_state.h`` but a few font/text related
    things are removed. Others are redined in the ``kiva_gl`` namespace.

    These two are removed:

            double character_spacing; //!! not sure about this type.
            kiva::text_draw_mode_e text_drawing_mode;

    This is removed:

            kiva::font_type font;

    The missing `font_type` might be related to the fact that the
    ``kiva::font_type`` is not changed to ``kiva_gl::font_type`` in
    ``kiva/gl/src/swig/font_type.i``
    """
    files = [
        # (from, to)
        ("kiva/agg/src/kiva_graphics_state.h", "kiva/gl/src/kiva_gl_graphics_state.h"),
    ]
    #show_diffs(files)
    ACCOUNTED_FOR.update(chain.from_iterable(files))


@register
def show_agg_src_kiva_to_kiva_gl_agg():
    """
    - Some files in kiva/agg/src are copied to kiva/gl/src/
      Defined namespace is changed from `kiva` to `kiva_gl`.
      Internal references to `agg24::` namespace is changed to `kiva_gl_agg::`.
    - For `kiva/gl/swig/affine_matrix.i`, numpy dependencies is changed to come
      from a local numpy.i, which is a brand new file.
    - For `kiva/gl/src/kiva_gl_rect.cpp`, the test code is removed.
    """
    duplicates = [
        # (from, to)
        ("kiva/agg/src/kiva_affine_helpers.cpp", "kiva/gl/src/kiva_gl_affine_helpers.cpp"),
        ("kiva/agg/src/kiva_affine_helpers.h", "kiva/gl/src/kiva_gl_affine_helpers.h"),
        ("kiva/agg/src/kiva_basics.h", "kiva/gl/src/kiva_gl_basics.h"),
        ("kiva/agg/src/kiva_compiled_path.cpp", "kiva/gl/src/kiva_gl_compiled_path.cpp"),
        ("kiva/agg/src/kiva_compiled_path.h", "kiva/gl/src/kiva_gl_compiled_path.h"),
        ("kiva/agg/src/kiva_dash_type.h", "kiva/gl/src/kiva_gl_dash_type.h"),
        ("kiva/agg/src/kiva_exceptions.h", "kiva/gl/src/kiva_gl_exceptions.h"),
        ("kiva/agg/src/kiva_font_type.cpp", "kiva/gl/src/kiva_gl_font_type.cpp"),
        ("kiva/agg/src/kiva_font_type.h", "kiva/gl/src/kiva_gl_font_type.h"),
        ("kiva/agg/src/kiva_graphics_context.cpp", "kiva/gl/src/kiva_gl_graphics_context.cpp"),
        ("kiva/agg/src/gl_graphics_context.h", "kiva/gl/src/kiva_gl_graphics_context.h"),
        ("kiva/agg/src/kiva_graphics_context_base.cpp", "kiva/gl/src/kiva_gl_graphics_context_base.cpp"),
        ("kiva/agg/src/kiva_rect.h", "kiva/gl/src/kiva_gl_rect.h"),
        ("kiva/agg/src/kiva_rect.cpp", "kiva/gl/src/kiva_gl_rect.cpp"),

        # swig code
        ("kiva/agg/src/affine_matrix.i", "kiva/gl/src/swig/affine_matrix.i"),
        ("kiva/agg/src/agg_std_string.i", "kiva/gl/src/swig/agg_std_string.i"),
        ("kiva/agg/src/sequence_to_array.i", "kiva/gl/src/swig/sequence_to_array.i"),
        ("kiva/agg/src/rgba_array.i", "kiva/gl/src/swig/rgba_array.i"),
        ("kiva/agg/src/rect.i", "kiva/gl/src/swig/rect.i"),
        ("kiva/agg/src/rgba.i", "kiva/gl/src/swig/rgba.i"),
        ("kiva/agg/src/constants.i", "kiva/gl/src/swig/constants.i"),
        ("kiva/agg/src/compiled_path.i", "kiva/gl/src/swig/compiled_path.i"),
    ]
    # show_diffs(duplicates)
    ACCOUNTED_FOR.update(chain.from_iterable(duplicates))


@register
def show_copied_vendored_code():
    """ Some files from kiva/agg/agg-24 (vendored) are copied and modified too.
    (allowed by the license)

    namespace agg24 is then changed to kiva_gl_agg
    """
    duplicates = [
        ("kiva/agg/agg-24/include/agg_color_rgba.h", "kiva/gl/src/agg/agg_color_rgba.h"),
    ]
    # show_diffs(duplicates)
    ACCOUNTED_FOR.update(chain.from_iterable(duplicates))


@register
def show_font_type():
    """ kiva/agg/src/font_type.i is copied to kiva/gl/src/swig/font_type.i
    but not all the changes I can explain. And there are missing changes if
    I try to compare this with other file.

    (1) The ``kiva::`` namespace is not changed to ``kiva_gl::``
    (2) The ``_agg`` private variable is renamed to ``_gl`` but I can't see
        where ``_agg`` or ``_gl`` are defined
        (compiled_path.i also has this ``_agg`` -> ``_gl`` change)
    """
    files = [
        # (from, to)
        ("kiva/agg/src/font_type.i", "kiva/gl/src/swig/font_type.i"),
    ]
    # show_diffs(files)
    ACCOUNTED_FOR.update(chain.from_iterable(files))


@register
def show_agg_src_kiva_to_kiva_gl():
    """
    These changes are basically:
        - Move _some_ of kiva/agg/src to kiva/gl/src
        - Then change `namespace kiva` to `namespace kiva_gl` for safety in case there is a symbol collision.
        - Some styling changes from `++i` to `i++` in for loops which should not matter.
        - References to `agg24::marker_e` is changed to `kiva_gl::marker_e`
    """
    moves = [
        # (from, to)
        ("kiva/agg/src/gl_graphics_context.h", "kiva/gl/src/kiva_gl_graphics_context.h")
    ]
    #show_diffs(moves)
    ACCOUNTED_FOR.update(chain.from_iterable(moves))


@register
def show_agg_24_moves():
    """
    These changes are basically:
        - Move _some_ of kiva/agg/agg-24/include to kiva/gl/src/agg/
        - Move _some_ of kiva/agg/agg-24/src to kiva/gl/src/agg/
        - Then change `namespace agg24` to `namespace kiva_gl_agg` for
        safety in case there is a symbol collision.
        - Some styling changes from `++i` to `i++` in for loops because
        they don't matter.
        - Line ending changes, could be IDE's doing.
    """
    moves = [
        # (from, to)
        ("kiva/agg/agg-24/include/agg_array.h", "kiva/gl/src/agg/agg_array.h"),
        ("kiva/agg/agg-24/include/agg_basics.h", "kiva/gl/src/agg/agg_basics.h"),
        ("kiva/agg/agg-24/src/agg_bezier_arc.cpp", "kiva/gl/src/agg/agg_bezier_arc.cpp"),
        ("kiva/agg/agg-24/include/agg_bezier_arc.h", "kiva/gl/src/agg/agg_bezier_arc.h"),
        ("kiva/agg/agg-24/include/agg_config.h", "kiva/gl/src/agg/agg_config.h"),
        ("kiva/agg/agg-24/include/agg_conv_transform.h", "kiva/gl/src/agg/agg_conv_transform.h"),
        ("kiva/agg/agg-24/include/agg_gamma_functions.h", "kiva/gl/src/agg/agg_gamma_functions.h"),
        ("kiva/agg/agg-24/include/agg_gamma_lut.h", "kiva/gl/src/agg/agg_gamma_lut.h"),
        ("kiva/agg/agg-24/include/agg_math.h", "kiva/gl/src/agg/agg_math.h"),
        ("kiva/agg/agg-24/include/agg_path_storage.h", "kiva/gl/src/agg/agg_path_storage.h"),
        ("kiva/agg/agg-24/src/agg_sqrt_tables.cpp", "kiva/gl/src/agg/agg_sqrt_tables.cpp"),
        ("kiva/agg/agg-24/src/agg_trans_affine.cpp", "kiva/gl/src/agg/agg_trans_affine.cpp"),
        ("kiva/agg/agg-24/include/agg_trans_affine.h", "kiva/gl/src/agg/agg_trans_affine.h"),
    ]
    #show_diffs(moves)
    ACCOUNTED_FOR.update(chain.from_iterable(moves))


@register
def test_gl_drawing():
    """ The entire test case is made to be skipped on Qt5 claimed to be
    motivated, but I doubt it is necessary - there are no evidence of segfault
    for that test case as far as I can tell.
    """
    ACCOUNTED_FOR.add("kiva/tests/test_gl_drawing.py")


@register
def test_qpainter_drawing():
    """ Two tests related to text segfault on Linux. Why are QPainter related
    tests affected by splitting GL from agg?
    """
    ACCOUNTED_FOR.add("kiva/tests/test_qpainter_drawing.py")


@register
def looks_okay():
    """
    """
    files = [
        # These files are license files
        "kiva/gl/LICENSES/LICENSE_Agg",
        "kiva/gl/LICENSES/LICENSE_Matplotlib",
        # New files are ignored because they are generated by the build tool (e.g.
        # ``pip install -e .``)
        ".gitignore",
        # Switch to use FakePygletContext... the name suggests it does
        # not depend on Pyglet, but it does.
        "enable/qt4/gl.py",
        "enable/wx/gl.py",
        # Remove OpenGL dependencies on OSX.
        # Also remove GL from the required build dependencies on Linux.
        # Compiling the code would fail anyway if GL dependencies are not
        # satisfied on Linux.
        "kiva/agg/setup.py",
        # The OpenGL dependencies are moved here.
        "kiva/gl/setup.py",
        # Add gl subpackage
        "kiva/setup.py",
        # These files are removed, they are probably not needed even on master
        "kiva/agg/src/gl_test/Lesson2.cpp",
        "kiva/agg/src/gl_test/Lesson2.h",
        "kiva/agg/src/gl_test/gl_test.cpp",
        "kiva/agg/src/gl_test/gl_test.vcproj",
        # References to the removed gl_test are also removed.
        "kiva/agg/src/kiva.sln",
        # References to removed files are removed
        "kiva/agg/src/kiva.vcproj",
        # Add kiva/gl files to source dist
        "MANIFEST.in",
        # Top-level includes
        "kiva/gl/gl.i",
    ]
    ACCOUNTED_FOR.update(files)


@register
def show_minor_changes():
    """ These files have some minor changes... not entirely sure why they are
    needed.
    """
    files = [
        # Not sure why `swapBuffers` is added.
        "enable/qt4/base_window.py",
    ]
    ACCOUNTED_FOR.update(files)


@register
def setup_may_have_missing_changes():
    """ Some files in kiva/agg/src/gl are moved to kiva/agg/src/osx/

    Old references to such as ``join("agg", "src", "gl", "plat_support.py")``
    may need to be updated to ``join("agg", "src", "osx", "plat_support.py")``
    """
    files = [
        "setup.py",
    ]
    ACCOUNTED_FOR.update(files)



if __name__ == "__main__":
    for func in CALLABLES:
        func()
    unaccounted_for = CHANGED_FILES - ACCOUNTED_FOR
    print(f"{len(unaccounted_for)} files unaccounted for: ")
    print(*sorted(unaccounted_for), sep="\n")
```

</details>

**Comment by jwiggins** [comment]
> In `kiva_gl_graphics_state.h`, the `font_type` is not defined in the `kiva_gl` namespace. The SWIG code for `kiva.gl.font_type` still refers to the `kiva::font_type`.

Good catch. I've corrected this and am also checking to see if it fixes the QPainter segfault.

> Why is the `numpy.i` added?

This is basically the same file as `kiva/agg/src/numeric.i` but with the Numeric compatibility stripped out. Numpy has been around for 15 years, so this _should_ be OK. 😉

> Should `GraphicsContext.save` raise an error or log a warning instead of doing nothing silently?

Yes, it would be nice if it did.

**Comment by jwiggins** [comment]
> checking to see if it fixes the QPainter segfault.

It did not.

**Comment by kitchoi** [comment]
Thank you @jwiggins for the update, and the latest commits (they look like the original commits from the beginning). The changes make sense. The only lingering issue is the segfault on the two text related tests for QPainter on Linux. I don't really have enough about the objectives of those QPainter tests to tell if the failures represent genuine issues we should worry about and what kind of impact downstream it would be. Apart from that, the rest looks good to me.

**Comment by rahulporuri** [comment]
FTR, looks like chaco is happy with the changes introduced in this PR - https://github.com/enthought/chaco/pull/561. Testing against another, larger,  internal project next.

**Review by rahulporuri — APPROVED** [review]
LGTM.

To be frank, I couldn't follow most (if not all) of the code changes - but in terms of functionality, i'm happy that the chaco testsuite and an internal project testsuite are both happy with the changes introduced in this PR. Given that, i'm okay with this being merged.

@jwiggins I'm not sure if there are improvements that can be made to the gl/agg backends beyond this PR - or if there are issues that weren't resolved in this PR which we want to address later on (like the QPainter tests segfaulting). Please consider opening additional issues as necessary to track any work that is needed in the future.

Finally, given the weight of changes made in this PR, it is probably best if we make a release candidate i.e. 5.0.0.rc1 (which should be shipped via pypi and edm) and then give our users a week or two to raise concerns before making the final 5.0.0 release.

**Comment by jwiggins** [comment]
Big thanks to @corranwebster, @kitchoi, and @rahulporuri for the reviews and feedback here. Let's keep moving.

**Pull request merged**
