### PR TITLE
[WIP] Add quartz files to sdist

### LINKED ISSUE #190: Many missing files in kiva.quartz in tarball
At least the following are required to build `kiva.quartz`, and are missing from the sdist tarball:

```
kiva/quartz/ABCGI.pyx
kiva/quartz/CTFont.pyx
kiva/quartz/CoreFoundation.pxi
kiva/quartz/CoreGraphics.pxi
kiva/quartz/CoreText.pxi
kiva/quartz/Python.pxi
kiva/quartz/c_numpy.pxd
kiva/quartz/mac_context.c
kiva/quartz/mac_context.h
kiva/quartz/mac_context_cocoa.m
kiva/quartz/numpy.pxi
```

### PR DESCRIPTION
**Pull request by itziakos**
fixes #190

@cournape is this ok?

### CODE REVIEW

**Comment by jwiggins** [comment]
I get this when I run `python setup.py sdist`:
```
reading manifest template 'MANIFEST.in'
warning: no files found matching 'chaco/tests/data/PngSuite/*.png'
warning: no files found matching 'chaco/tests/data/PngSuite/LICENSE.txt'
warning: manifest_maker: MANIFEST.in, line 4: unknown action 'kiva/quartz/*.pyx'

warning: manifest_maker: MANIFEST.in, line 5: unknown action 'kiva/quartz/*.pxi'

warning: manifest_maker: MANIFEST.in, line 6: unknown action 'kiva/quartz/*.pxd'

warning: manifest_maker: MANIFEST.in, line 7: unknown action 'kiva/quartz/mac_context.c'

warning: manifest_maker: MANIFEST.in, line 8: unknown action 'kiva/quartz/mac_context.h'

warning: manifest_maker: MANIFEST.in, line 9: unknown action 'kiva/quartz/mac_context_cocoa.m'
```

BUT, All of the specified files are in the tarball which is created.

Although, when I create an sdist using the master branch, I also get the specified files. I'm not really sure what to make of that...

**Comment by jwiggins** [comment]
`chaco/tests/data/PngSuite/...` WTF. I bet I even signed off on that change...

**Comment by itziakos** [comment]
let me have a look again, I think I am doing someting stupid

**Comment by itziakos** [comment]
it should be ok now

**Comment by itziakos** [comment]
need to add a few more fiels to sdist

**Comment by itziakos** [comment]
closing will make a PR against master

**Pull request closed without merging**
