### PR TITLE
fixes for recent swig

### PR DESCRIPTION
**Pull request by jjstickel**
Recent version of swig (3.0.5) broke the build of enable. This pull request fixes the issue. See https://github.com/swig/swig/issues/221#issuecomment-54469375

### CODE REVIEW

**Comment by itziakos** [comment]
:+1:

**Comment by jwiggins** [comment]
Ahh... Thanks for the patch!

Unfortunately, Travis-CI is only telling us that it doesn't break on older versions of swig:
```
Setting up swig2.0 (2.0.4+really2.0.4-4ubuntu2) ...
Setting up swig (2.0.4+really2.0.4-4ubuntu2) ...
```

@itziakos : Did you test this?

**Comment by itziakos** [comment]
Not locally, I thought that travis was checking that version. Sorry.

**Comment by jwiggins** [comment]
Ahh... OK. I `grin`'d the current code. These four files are the only place where `%pythoncode` is being used in a slightly bad (but allowed by older swig) way. Based on that, there should be zero downside to merging this.

**Comment by jwiggins** [comment]
Thanks @jjstickel!

**Pull request merged**
