### PR TITLE
Add points_in_polygon to kiva.agg with DeprecationWarning

### PR DESCRIPTION
**Pull request by jwiggins**
@rkern: As requested.

I'm depending a bit on CI here to test this since I was having 2to3 problems locally (in other modules).

### CODE REVIEW

**Comment by jwiggins** [comment]
enthought/traitsui#369 should fix the broken CI run seen here...

**Comment by jwiggins** [comment]
All the yaks have been shaved. I added a unit test.

**Comment by jwiggins** [comment]
I moved the code to `kiva/agg/__init__.py` and fixed the unit test. Should be all good now. :crossed_fingers:

**Comment by rkern** [comment]
LGTM! Thanks!

**Pull request merged**
