### PR TITLE
Kiva explorer demo

### PR DESCRIPTION
**Pull request by corranwebster**
Add a really simple traitsui view for playing with Kiva.

screen shot 2016-10-26 at 9 30 24 am

### CODE REVIEW

**Comment by jwiggins** [comment]
:heart_eyes:

Bless you, sir. This is exactly what I need right now.

I should probably push my pyagg backend branch, huh?

**Comment by jwiggins** [comment]
Just a quick read from my end, but LGTM

**Comment by corranwebster** [comment]
You're welcome!  And since this is non-critical code, I shall merge it.

**Comment by eric-jones** [comment]
It would be useful to have something that printed out the rendering time on this... (per render and frames per second)

**Pull request merged**
