### PR TITLE
Add links to benchmark image outputs

### LINKED ISSUE #649: Kiva Benchmark: Add links to image outputs
The results table should have links to the generated images.

### PR DESCRIPTION
**Pull request by jwiggins**
Fixes #649

### CODE REVIEW

**Review by rahulporuri — COMMENTED** [review]
I tested this locally and it looks like 1x and 2x are swapped around - the filename says 2x but the image is actually 1x and viceversa.

**Review by rahulporuri — APPROVED** [review]
LGTM. I tested this locally and it works as expected.

**Comment by rahulporuri** [comment]
Is this the issue with the qpainter backend `draw_rect` you were referring to - 
qpainter draw_rect 2x

**Comment by jwiggins** [comment]
> Is this the issue with the qpainter backend `draw_rect` you were referring to

That's the one.

**Comment by jwiggins** [comment]
Thanks for the review

**Comment by rahulporuri** [comment]
created the issue https://github.com/enthought/enable/issues/657 - this sounds like a blocker for switching the default backend from agg to celiagg.

**Comment by jwiggins** [comment]
This is a QPainter problem. Switching to celiagg wouldn't change anything

**Comment by rahulporuri** [comment]
im sorry. im not in the right headspace right now

**Comment by jwiggins** [comment]
Don't sweat it

**Pull request merged**
