### PR TITLE
Release 4.8.0

### PR DESCRIPTION
**Pull request by jwiggins**
Once this looks good, I'll tag the commit and unflip the release flag in `setup.py`.

### CODE REVIEW

**Comment by corranwebster** [comment]
Generally looks good - I have done a quick documentation PR #352 that you may want to merge into this.

**Comment by jwiggins** [comment]
OK, last minute fixes are in. This is ready for a final look!

**Comment by corranwebster** [comment]
LGTM as far as PR goes; I fixed up #317 if you want to double check it and include that in the release as well.

**Comment by jwiggins** [comment]
#317 is in now

**Pull request merged**
