### PR TITLE
Backport bugfixes from master

### PR DESCRIPTION
**Pull request by mdickinson**
[Note: PR is against a newly-created maint/4.6.x branch, created from the 4.6.1 release tag, with its version bumped and `IS_RELEASED` set to `False`.]

Backport commits from PRs #268, #269 and #272, in preparation for a 4.6.2 release.

### CODE REVIEW

**Comment by corranwebster** [comment]
Test failures are odd.  Has a dependency shifted from under us?

Other than that, generally the PR looks good.

**Comment by corranwebster** [comment]
Also, I don't think it matters, but you are branched from the release point, not the commit where release is set to `False`: https://github.com/enthought/enable/blob/backport-bugfixes-from-master/setup.py#L42

**Comment by mdickinson** [comment]
> but you are branched from the release point

Yep. I was following the contribution guide.

> then a branch should be created from the release tag [...]

**Comment by mdickinson** [comment]
Note that #272 was also merged with CI failures; we may need to fix that upstream and then backport.

**Comment by corranwebster** [comment]
If I have a suspect, it would be that CI is tracking Pyface and TraitsUI master.  It might make sense for the maintenance branch to track the most recent released versions.

**Comment by corranwebster** [comment]
Regarding the branch point, I would have started at #c7fb14a2a375b981e8e67d0b7e6efc14fa1974a5 rather than #5652a32f3a4d60d9778ed8d15b37c5a5b65cdefe

I think that the comment is referring to creating the maint/4.6.x branch.

**Comment by mdickinson** [comment]
> I think that the comment is referring to creating the maint/4.6.x branch.

Ah, sorry; I thought that was what you were talking about, too. Yes, I should have branched from #c7fb14a, and would have done if I'd thought to create #c7fb14a _before_ I started working on the backports. As you say, I think it doesn't matter, but I can recreate this PR against #c7fb14a if you prefer.

**Comment by mdickinson** [comment]
> It might make sense for the maintenance branch to track the most recent released versions.

Agreed, though I think it's PySide that's causing the issues with 3.4.

Opened #274 and #275 for the CI issues; those probably need to be resolved before this can move forward.

**Comment by mdickinson** [comment]
At the risk of flogging a dead horse, I originally understood your message to mean that I should have branched `maint/4.6.x` from 32c2a014986c6f243b369347387cc555d34f751f. (Which seems like a good idea to me.)

**Comment by mdickinson** [comment]
Restarted the Travis builds: now it's only the 3.4 Qt builds that are failing.

@jwiggins: I'd like to make an Enable 4.6.2 release from this branch. Does that sound reasonable? It's mainly for an internal project that's running into the missing fonts issue fixed in #272.

**Comment by mdickinson** [comment]
> I'd like to make an Enable 4.6.2 release from this branch.

Sorry, correction: I'd like to make an Enable 4.6.2 release from the release maintenance branch, not from this one.

Merging this branch, now that at least half of the CI issues are solved.

**Pull request merged**
