### PR TITLE
Fix typo in MANIFEST.in

### PR DESCRIPTION
**Pull request by mdickinson**
recusive -> recursive

### CODE REVIEW

**Comment by jwiggins** [comment]
Nice catch!

**Comment by mdickinson** [comment]
> Please use "Squash and Merge" since this branch contains a GitHub signed commit

Will do, but what's the relevance of the signed commit?

**Comment by jwiggins** [comment]
It makes it easier to collect merge commits when preparing a release:
`git log --reverse --merges --first-parent --pretty=format:%s <last release>...master`
will catch all the merge commits, but none of the squash merges.

However! We're using GitHub to manage this project, and so the vast majority of PR merges are done via GitHub (because we haven't protected the master yet branch for some reason). GitHub signs all of its commits, so they can easily be found with:
`git log --reverse --pretty=format:"%G?: %s" <last release>...master | grep "^[^N]:"`

**Comment by mdickinson** [comment]
Got it. Thanks.

**Comment by jwiggins** [comment]
Also, squash merges are the [preferred merge strategy](https://github.com/enthought/enable/blob/master/CONTRIBUTING.rst#branches-and-releases) for this repo:

**Pull request merged**
