### PR TITLE
Remove the old and outdated Pyglet and VTK backends

### PR DESCRIPTION
**Pull request by jwiggins**
Both backends have been mostly inaccessible since the refactor in d3aa65bb8e14d2224ed78ef80c578a4b0f00b087 (just a short 10 years ago)

### CODE REVIEW

**Review by rahulporuri — APPROVED** [review]
The changes LGTM but i'm not entirely sure what you mean by "Both backends have been mostly inaccessible since the refactor in d3aa65b (just a short 10 years ago)".

I searched for uses of the pyglet and vtk backends on github and i couldn't find any.

It might be better to have this approved by a higher authority (maybe @corranwebster , @mdickinson , @rkern )?

**Comment by jwiggins** [comment]
Yes. I'd prefer to hear the opinion of them before merging this.

**Comment by rkern** [comment]
I think these backends can go. The projects that did use them are long-dormant. With the macOS deprecation of OpenGL, I think we'll probably need to start from scratch if we want this kind of functionality in the future.

**Comment by jwiggins** [comment]
Thanks for the feedback

**Pull request merged**
