### PR TITLE
Added python 3.5 and 3.6 as targets

### LINKED ISSUE #274: Continuous integration broken on Python 3.x / Qt+PySide
Travis CI seems to be broken on Python 3.x with PySide: the `./build_pyside_wheel.sh` script fails when initializing git submodules. I can reproduce the failure locally (OS X 10.9.5, Python 3.4 from EDM):
```
(test34)(edm)bash-3.2$ python --version
Python 3.4.5 -- Enthought, Inc. (x86_64)
(test34)(edm)bash-3.2$ ./build_pyside_wheel.sh 
Building PySide
Cloning into 'pyside-setup'...
remote: Counting objects: 889, done.
remote: Total 889 (delta 0), reused 0 (delta 0), pack-reused 889
Receiving objects: 100% (889/889), 339.45 KiB | 454.00 KiB/s, done.
Resolving deltas: 100% (540/540), done.
Cleared directory 'sources/pyside'
Cleared directory 'sources/pyside-examples'
Cleared directory 'sources/pyside-tools'
Cleared directory 'sources/shiboken'
rm 'sources/pyside'
rm 'sources/shiboken'
Cloning into '/Users/mdickinson/Desktop/enable/pyside-setup/sources/shiboken'...
remote: Counting objects: 15693, done.
remote: Total 15693 (delta 0), reused 0 (delta 0), pack-reused 15693
Receiving objects: 100% (15693/15693), 4.44 MiB | 1.09 MiB/s, done.
Resolving deltas: 100% (12312/12312), done.
Cloning into '/Users/mdickinson/Desktop/enable/pyside-setup/sources/pyside'...
remote: Counting objects: 19704, done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 19704 (delta 22), reused 0 (delta 0), pack-reused 19655
Receiving objects: 100% (19704/19704), 7.79 MiB | 1.47 MiB/s, done.
Resolving deltas: 100% (13933/13933), done.
Synchronizing submodule url for 'sources/pyside'
Synchronizing submodule url for 'sources/shiboken'
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-7.0.zip
Extracting in /var/folders/6d/lyq0l1nx3c74lk1lkr4z7hn80000gn/T/tmp9aql3r1f
Now working in /var/folders/6d/lyq0l1nx3c74lk1lkr4z7hn80000gn/T/tmp9aql3r1f/setuptools-7.0
Building a Setuptools egg in /Users/mdickinson/Desktop/enable/pyside-setup
/Users/mdickinson/Desktop/enable/pyside-setup/setuptools-7.0-py3.4.egg
Initializing submodules for PySide version 1.2.2
Submodule 'sources/pyside-examples' (https://github.com/PySide/Examples.git) registered for path 'sources/pyside-examples'
Submodule 'sources/pyside-tools' (https://github.com/PySide/Tools.git) registered for path 'sources/pyside-tools'
Cloning into '/Users/mdickinson/Desktop/enable/pyside-setup/sources/pyside-examples'...
Cloning into '/Users/mdickinson/Desktop/enable/pyside-setup/sources/pyside-tools'...
Submodule path 'sources/pyside-examples': checked out '050809faad4e8f58e89ab53df9e3f86045f98c48'
Submodule path 'sources/pyside-tools': checked out 'edcad2b4f3c7c6dc12b8774c931600bf11363707'
Entering 'sources/pyside'
Entering 'sources/pyside-examples'
Entering 'sources/pyside-tools'
Entering 'sources/shiboken'
Entering 'sources/pyside'
fatal: Couldn't find remote ref master
Stopping at 'sources/pyside'; script returned non-zero status.
Traceback (most recent call last):
  File "setup.py", line 240, in <module>
    raise DistutilsSetupError("Failed to initialize the git submodules")
distutils.errors.DistutilsSetupError: Failed to initialize the git submodules
```

### PR DESCRIPTION
**Pull request by jdeschenes**
Seems like it will fix #274 as well.

### CODE REVIEW

**Comment by jdeschenes** [comment]
How do you propose to fix the build error for python 3 and qt?

**Comment by jwiggins** [comment]
See #281. I'll merge that soon and then this branch will need to be rebased/adapted

**Comment by jdeschenes** [comment]
No problem. The changes in this branch are very minor.

**Comment by jdeschenes** [comment]
Is there any reason why pyqt is not tested during the travis CI run?

**Comment by jwiggins** [comment]
I think that's a relic of the days when it was thought that PySide would be the Qt binding going forward.... but don't quote me on that.

**Comment by jwiggins** [comment]
This should only need an update to `.travis.yml` now that #281 is merged

**Comment by jwiggins** [comment]
LGTM!

**Pull request merged**
