### PR TITLE
Fix warnings from the documentation build

### PR DESCRIPTION
**Pull request by jwiggins**
Doing a full build of the documentation with autodoc generation was spitting out some warnings, so I squashed them.

### CODE REVIEW

**Review by rahulporuri — APPROVED** [review]
This PR LGTM. The only sphinx warnings I observed were related to missing libraries (`wx` and `svg`).

**Comment by rahulporuri** [comment]
But, I wasn't able to build the docs as-is on this branch. Might have something to do with #757 .

```
[EXECUTING] edm run -e enable-test-3.6-pyqt5 -- sphinx-build -b html -d build/doctrees source build/html
Running Sphinx v2.3.1

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "C:\Users\rporuri\.edm\envs\enable-test-3.6-pyqt5\lib\site-packages\sphinx\config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "C:\Users\rporuri\.edm\envs\enable-test-3.6-pyqt5\lib\site-packages\sphinx\util\pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "C:\Users\rporuri\work\github\ets\enable\docs\source\conf.py", line 62, in <module>
    version = release = runpy.run_path(version_file)['full_version']
  File "C:\Users\rporuri\.edm\envs\enable-test-3.6-pyqt5\lib\runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Users\rporuri\.edm\envs\enable-test-3.6-pyqt5\lib\runpy.py", line 231, in _get_code_from_file
    with open(fname, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\rporuri\\work\\github\\ets\\enable\\docs\\source\\..\\..\\enable\\_version.py'
```

**Comment by jwiggins** [comment]
😩 Isn't that what we were trying to fix?

**Comment by jwiggins** [comment]
I see the problem... That's different than what #757 was doing. It's fixed now.

**Comment by jwiggins** [comment]
Thanks for the testing

**Pull request merged**
