### PR TITLE
Release 5.0.0rc2

### PR DESCRIPTION
**Pull request by jwiggins**
This is the 5.0.0rc2 release. I've added #597 to the mix here, because documentation is always a welcome addition 😉.

### CODE REVIEW

**Review by rahulporuri — APPROVED** [review]
Changes LGTM. Looks like the plan is to not squash merge this PR so that we can tag the specific release commit which sets the `IS_RELEASED` flag?

**Comment by jwiggins** [comment]
> Looks like the plan is to not squash merge this PR

Correct. I've been sticking to rebase & merge for PRs targeting this release branch.

**Comment by jwiggins** [comment]
Merged. Tagged. Thanks @rahulporuri!

**Comment by rahulporuri** [comment]
https://github.com/enthought/enable/issues/601 was the reason why the release took 10 mins instead of 5 mins (or less).

**Pull request merged**
