### PR TITLE
Make 4.6.2 release.

### PR DESCRIPTION
**Pull request by mdickinson**
PR for 4.6.2 release.

@jwiggins: do you have time to review / comment?

### CODE REVIEW

**Comment by jwiggins** [comment]
Looks like the build failure is a result of CI complexity and not enable?
```
Cloning into 'sources/shiboken'...

remote: Invalid username or password.

fatal: Authentication failed for 'https://github.com/PySide/shiboken2.git/'

Clone of 'https://github.com/PySide/shiboken2.git' into submodule path 'sources/shiboken' failed

The command "if [[ ${TRAVIS_PYTHON_VERSION} == "3.4" && ${ETS_TOOLKIT} == "qt4" ]]; then ./build_pyside_wheel.sh; fi" failed and exited with 1 during .
```

**Comment by jwiggins** [comment]
But no objections to a release.

**Comment by mdickinson** [comment]
@jwiggins: Thanks! Yes, I believe the build failure to be independent of the PR. There's a corresponding issue open at #274.

**Comment by mdickinson** [comment]
Same CI failures as before (issue #274) on Python 3.4+Qt4+PySide; everything else is passing.

I'll merge this PR, and tag 248cf7adee2cfc4cdf07646a6f47ce5f13a358df as `4.6.2`.

**Comment by mdickinson** [comment]
> I'll merge this PR, and tag 248cf7a as 4.6.2.

Done.

```
taniyama:enable mdickinson$ git show 4.6.2
tag 4.6.2
Tagger: Mark Dickinson <mdickinson@enthought.com>
Date:   Tue Jun 6 13:49:34 2017 +0100

Version 4.6.2

commit 248cf7adee2cfc4cdf07646a6f47ce5f13a358df (tag: 4.6.2)
Author: Mark Dickinson <mdickinson@enthought.com>
Date:   Mon Jun 5 13:10:43 2017 +0100

    Bump version info for 4.6.2 release.

diff --git a/setup.py b/setup.py
index c6d1bec..93c88bb 100644
--- a/setup.py
+++ b/setup.py
@@ -39,7 +39,7 @@ MAJOR = 4
 MINOR = 6
 MICRO = 2
 
-IS_RELEASED = False
+IS_RELEASED = True
 
 VERSION = '%d.%d.%d' % (MAJOR, MINOR, MICRO)
 
```

**Comment by jwiggins** [comment]
:+1:

**Comment by mdickinson** [comment]
PyPI upload is in progress...

**Comment by mdickinson** [comment]
> PyPI upload is in progress...

Well, it was, until I discovered that since [PEP 527](https://www.python.org/dev/peps/pep-0527/), only one source distribution format can be uploaded to PyPI. That leaves us choosing between .tar.gz and .zip, and we should probably be consistent with our choices across all ETS packages.

@corranwebster, @jwiggins: Any strong opinions about whether we should upload `.zip` or `.tar.gz`?

**Comment by mdickinson** [comment]
Okay, I've just read an excruciatingly long [distutils-sig thread](https://mail.python.org/pipermail/distutils-sig/2016-August/029384.html) on the subject, which appears to boil down to:
- .tar.gz is the now
- .zip is the ill-defined future, probably with a rename to .sdist
- there's little to choose between them technically, but .tar.gz currently has the weight of (a) numbers, and (b) Donald Stufft and Nick Coghlan.

So I'm making an executive decision and going with .tar.gz.

**Pull request merged**
