### PR TITLE
Remove support for Mac font suitcases.

### PR DESCRIPTION
**Pull request by mdickinson**
This PR removes Mac-only support for font suitcases. That support was enabled only for classic Mac OS, and depends on the `macfs` std. lib. module, which doesn't exist in Python 3.

### CODE REVIEW

**Comment by corranwebster** [comment]
LGTM, although in the grand scheme of things we probably would be better off if we didn't have a vendorised 8+ year old version of fonttools (https://pypi.python.org/pypi/FontTools) bundled up into Enable.

**Comment by jwiggins** [comment]
@corranwebster: Do you think we can/should switch to a non-vendorized version? This would be something to think about post-release, of course

**Comment by corranwebster** [comment]
@jwiggins I have no idea: I haven't looked into it at all.  The likelihood of success will probably be based on how much the code has been modified.  If its just bugfixes and styling, it may just be a matter of fixing up imports.

**Comment by jwiggins** [comment]
@mdickinson: LGTM
@corranwebster: I'll add an issue

**Pull request merged**
