### PR TITLE
README: Update badge and links

### PR DESCRIPTION
**Pull request by hugovk**
* Update links to use HTTPS / new addresses
* Use SVG coverage badge for consistency

# Before

image

# After

image

### CODE REVIEW

**Comment by hugovk** [comment]
The CI failure is unrelated and caused by things like:

```
    from traitsui.tests._tools import skip_if_null
ImportError: cannot import name 'skip_if_null'
```


The last passing CI build was 6 months ago with:
```
traitsui     6.1.3-5       1.52  MiB  *
```

Now it's had a major bump:

```
traitsui     7.0.1-2       1.57  MiB  *
```

I suggest enabling a Travis CI cron job to catch these things a bit sooner:

* https://docs.travis-ci.com/user/cron-jobs/

**Comment by kitchoi** [comment]
Thank you @hugovk for your contributions!

> The CI failure is unrelated and caused by things like:
>
>    from traitsui.tests._tools import skip_if_null
ImportError: cannot import name 'skip_if_null'

I have opened #425 to track. It should be fixed separately.
I will restart the CI for this PR as it should be green on master now.

> I suggest enabling a Travis CI cron job to catch these things a bit sooner:

Yep, agreed.

**Comment by kitchoi** [comment]
Ah I am sorry, I think we need to merge master in here in order to refresh the Travis CI configuration. Rebuilding previous job reuses the previous outdated configuration.

Other than that I think the changes here look good. All the links work: a previously broken link is now working.

**Review by kitchoi — APPROVED** [review]
LGTM

**Comment by hugovk** [comment]
Rebased on master!

**Comment by kitchoi** [comment]
Thank you very much!

**Pull request merged**
