### PR TITLE
Update gh-pages to 4.5.0

### PR DESCRIPTION
**Pull request by itziakos**

### CODE REVIEW

**Comment by itziakos** [comment]
@corranwebster , @jwiggins, can you have a quick look?

**Comment by corranwebster** [comment]
Looks reasonable to me.

What was the reason for adding to the `.gitignore`?

**Comment by itziakos** [comment]
When switching between the branch where the documentation was build and the gh-pages branch. You end up with added folders in the status report. It is just confusing and it would be also wrong to commit these files by mistake.

**Comment by jwiggins** [comment]
LGTM

**Pull request merged**
