### PR TITLE
FIX: affine transformation trs_factor

### PR DESCRIPTION
**Pull request by pberkes**
The calculation to find the transformation parameters
for a translation/rotation/scale transformation were
in fact for a translation/scale/rotation one.

The test only passed because of the particular combination of parameters used.

### CODE REVIEW

**Comment by jwiggins** [comment]
@pberkes: If you have a minute, can you fix the merge conflict here? I think it would be nice to get this into the next release.

**Comment by mdickinson** [comment]
@jwiggins: I suspect that @pberkes is no longer watching these issues (he's no longer at Enthought).

**Comment by pberkes** [comment]
I'm watching, I'm watching. But I never got around testing PS and SVG...

**Comment by jwiggins** [comment]
Don't worry about PS and SVG right now. I think the tests you added are adequate.

**Comment by mdickinson** [comment]
> I'm watching, I'm watching.

Good to know! Sorry for the misinformation.

**Comment by pberkes** [comment]
Argh I don't have push rights anymore :-( creating fork...

**Comment by corranwebster** [comment]
@pberkes if you plan to continue being active on ETS projects we can get you push rights.

**Comment by pberkes** [comment]
hard to say what's going to happen from next week, let me fork for now

**Comment by pberkes** [comment]
Closing, resubmitting from fork

**Pull request closed without merging**
