### PR TITLE
Release 4.6.0

### PR DESCRIPTION
**Pull request by jwiggins**
@corranwebster, @jvkersch: I'm starting this now.

### CODE REVIEW

**Comment by corranwebster** [comment]
Let me know when you want me to upload to PyPI.

**Comment by jwiggins** [comment]
OK. I've built an sdist locally and tested that it works on Linux. If you'd like to test on OS X, that might be good.

The docs build also looks good.

**Comment by corranwebster** [comment]
Tested on OS X. Looks good.  Uploaded to PyPI: https://pypi.python.org/pypi/enable/4.6.0

You can go ahead and tag 9bc2198 as the release.

**Comment by jwiggins** [comment]
Excellent. I've bumped the version once more.

Actually, I want to touch the changelog file before merging here.

**Comment by jwiggins** [comment]
Any reason _not_ to merge this?

**Comment by corranwebster** [comment]
No reason not to merge it.

**Pull request merged**
