### PR TITLE
Made the test examples run on windows and using wxpython4

### LINKED ISSUE #393: Method should have "self" as first argument.
https://github.com/enthought/enable/blob/6cf525cbeefdf34dc6eac5e54d7a73f755ea79b1/kiva/abstract_graphics_context.py#L336

### LINKED ISSUE #395: Dangerous default value [] as argument in enable/enable/savage/svg/backends/kiva/renderer.py
The __init__ method has a dangerous default value [] as argument for "transforms":

https://github.com/enthought/enable/blob/6cf525cbeefdf34dc6eac5e54d7a73f755ea79b1/enable/savage/svg/backends/kiva/renderer.py#L172-L173

Consider setting it to None and check for None explicitly.

### LINKED ISSUE #396: range expects an int in argument, but gets a float in enable/kiva/agg/freetype2/src/tools/docmaker/tohtml.py
range expects an int in argument on line 521, but gets float from non-floor division (change to // for floor division in Python 3  otherwise it will crash on passing a float): 

https://github.com/enthought/enable/blob/6cf525cbeefdf34dc6eac5e54d7a73f755ea79b1/kiva/agg/freetype2/src/tools/docmaker/tohtml.py#L512-L522

### LINKED ISSUE #399: wx.GraphicsRenderer_GetDefaultRenderer does not exist in wxpython 4
https://github.com/enthought/enable/blob/6cf525cbeefdf34dc6eac5e54d7a73f755ea79b1/enable/savage/svg/backends/wx/renderer.py#L159

replace with wx.GraphicsRenderer.GetDefaultRenderer

### LINKED ISSUE #400: Examples does not work correctly
For example when running [examples/demo.py](https://github.com/enthought/enable/blob/6cf525cbeefdf34dc6eac5e54d7a73f755ea79b1/examples/demo.py#L25) and clicking on the "Example"->"Savage"->"Toggle demo" the window does not show in the demo tab, but rather as a standalone window.
The "Example"->"Savage"->"Static image"  or "Example"->"Savage"->"Buttons on canvas" does not show at all. 

In this test I am using the wx backend and:
Operating system: Windows 10 64bit
wxPython version & source: wxpython 4.0.7.post2 (https://anaconda.org/conda-forge/wxpython)
Python version & source: Python 3.7.4 (default, Aug 9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] (Anaconda)

### PR DESCRIPTION
**Pull request by pbrod**
Fixes #400 Made the test examples run on windows and using wx:
 * Replaced deprecated "wx.EVT_XXX(panel, handler)" with "panel.Bind(wx.EVT_XXX, handler)" in   rgba_color_editor.py
 * Replaced faulty "slider.SetTickFreq( 10, 1 )" with "slider.SetTickFreq(10)" in rgba_color_editor.py
 * Fixed the failing ToolkitEditorFactory.all_facenames method in kiva_font_editor.py
 * Replaced deprecated wx.PyPanel with wx.Panel
 * Insulated the xxxtrait.configure_traits() call inside a "if __name__ == '__main__'" block
 * Added the "demo = XXXtrait()" to each demo-script so it can be discovered and run by the traitsui.extra.demo.demo.
 * Changed "from enable.wx_backend import Window" to "from enable.api import Window"
and moved all imports to the top of the file.
 * Replaced call to wx.SystemSettings_GetMetric with wx.SystemSettings.GetMetric
 * Replaced call to deprecated wx.EVT_XXXX( control, self._on_XXXX) with control.Bind(wx.EVT_ERASE_BACKGROUND, self._on_XXXXX)
 * Fixed a bug in BaseWindow._create_control: If parent is None it is set to wx.Frame(None) in order to avoid crash in the unittests.
 * Replaced wx.WXK_PRIOR and wx.WXK_NEXT (which does not exist on wxpython4) with wx.WXK_PAGEUP and wx.WXK_PAGEDOWN
 * Added missing player_play.svg and player_pause.svg to examples/savage folder (LGPL license)

Fixes #399 replaced:
 * wx.GraphicsRenderer_GetDefaultRenderer with wx.GraphicsRenderer.GetDefaultRenderer
 * wx.GraphicsContext_Create with wx.GraphicsContext.Create

Fixes #396 Made sure rows and columns are integers by replacing "/" with "//" in kiva/agg/freetype2/src/tools/docmaker/tohtml.py

Fixes #395
 * Replaced dangerous default value "transforms=[]" with "transforms=None" in __init__ methods.

Fixes #393 Added self as first argument to AbstractGraphicsContext.draw_image method

Fixed failing examples:
 * examples/kiva/agg/benchmark.py (Float -> float, added missing import of  zeros)
 * examples/kiva/agg/polygon_hit_test.py (point_in_polygon -> points_in_polygon)
 * examples/kiva/gradient.py (added missing import of tempfile)

Moved code in 'if __name___ == "__main__"' block in benchmark.py to the run_all_benchmarks function.

Removed unused stuff:
 * Removed unused import of "FILL_STROKE" in examples/kiva/agg/compiled_path.py
 * Removed unused import of "affine", "constants" in examples/kiva/agg/dummy.py
 * Removed unused ttfdict_to_fnames function in font_manager.py
 * Removed unused import of "sqrt" and "affine" in enable/savage/svr/backends/kiva/renderer.py

Replaced call to deprecated time.clock with time.perf_counter on Python 3 in:
 * examples/kiva/agg/benchmark.py
 * examples/kiva/agg/dash.py
 * examples/kiva/agg/lion.py
 * examples/kiva/agg/pylygon_hit_test.py
 * examples/kiva/agg/simple_clip.py
 * examples/kiva/agg/text_ex.py
 * examples/kiva/simple.py
 * examples/kiva/test_image3.py

Other fixes:
* Readded two tests in kiva/agg/tests/test_save.py and moved two skipped tests to expected failure and also removed unused import of "allclose" and "nose".
 * Made wx.VERSION comparison more robust in enable/savage/svg/backends/wx/renderer.py, enable/wx/base_window.py and enable/wx/constants.py.
 * Python style fixes here and there.

### CODE REVIEW

**Comment by jwiggins** [comment]
This is great. Thanks for the contribution!

As it's a bit large and addresses several different issues, I'm going to break it up into multiple PRs.

**Comment by pbrod** [comment]
Ok.

**Comment by rahulporuri** [comment]
Looks like there are more changes in this PR than in #402 and #403. I'll try merging master into this branch.

**Comment by jwiggins** [comment]
> Looks like there are more changes in this PR than in #402 and #403.

I'm pretty sure I explicitly avoided some changes when building the branches for #402 and #403. If you see something worth extracting, then do that. Otherwise 👎

**Comment by kitchoi** [comment]
Thank you @pbrod for the contribution!

I believe the fixes brought by this PR have been merged to the development branch via the breakout PRs @jwiggins opened (and @pbrod is a co-author). This branch has now, understandably, become largely unmergeable due to merge conflicts. If there are anything we missed and should be extracted into a separate PR, we can come back to this PR that is now recorded.

Is that alright if we close this PR? @jwiggins @pbrod

**Comment by rahulporuri** [comment]
Closing this PR now that we've extracted all of the relevant bits from it into separate PRs. Thanks again @pbrod for the contribution.

**Pull request closed without merging**
